### ISSUE TITLE
This library prevents me from using OCaml 4.08's Result module

### ISSUE THREAD

**Issue by alan-j-hu** [janestreet/result#8]
When I have this library as a dependency (including as a transitive one), I can't use the `Result` library from OCaml 4.08. However, I can work around it by doing `Stdlib.Result`.

[result-bug.tar.gz](https://github.com/janestreet/result/files/3443054/result-bug.tar.gz)

As this library already checks the OCaml version, perhaps it could check for OCaml 4.08 and `include` the standard library's `Result` module.

**Comment by hhugo** [comment]
What about we make installing `result` on ocaml >= 4.08 a no-op

**Comment by hcarty** [comment]
Are there any issues with @hhugo's [suggestion](https://github.com/janestreet/result/issues/8#issuecomment-526885722) to make `result` installation a no-op on newer OCaml versions?  It would be nice to not need to `open Stdlib` to get around the `result` package clobbering the `Result` module.

**Comment by hongchangwu** [comment]
I believe making `result` installation a no-op on ocaml >= 4.08 will break existing packages that use `result`. The result type from this package is called `Result.result` while the one from `Stdlib` is called `Result.t`.

**Comment by hcarty** [comment]
@hongchangwu That's a very good point.  Rather than making it a no-op, are there any issues with this library defining `Result` under OCaml >= 4.08.0 as:
```ocaml
include Result
type ('ok, 'error) result = ('ok, 'error) t
```
It would be nice to not have to hack around this shadowing when using newer OCaml releases.

**Comment by aantron** [comment]
The `t` alias should be added to all versions (while `include Result` only on >= 4.08).

**Comment by aantron** [comment]
I'll send a PR in the coming days.
